# https://github.com/antonputra/lesson-087/blob/main/.github/workflows/gcp.yml
---
name: Update Artifact Registry
on:
  push:
    branches: [main]
jobs:
  build-push-artifact-registry:
    name: Update Artifact Registry
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: goba2
      GCP_PROJECT: holmes-dev
      GCP_REGISTRY: holmes-container-registry
      GCP_REGION: northamerica-northeast1
    steps:
      - name: "GCP Checkout"
        uses: actions/checkout@v2

      - name: "GCP Setup"
        uses: "google-github-actions/setup-gcloud@v0"

      - name: "GCP Auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "GCP Config"
        run: |-
          gcloud info
          gcloud auth configure-docker $GCP_REGION-docker.pkg.dev --quiet

      - name: "Docker Build"
        run: docker image build -t goba2:latest .

      - name: "Docker Push"
        run: |-
          docker tag $IMAGE_NAME:latest $GCP_REGION-docker.pkg.dev/$GCP_PROJECT/$GCP_REGISTRY/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest $GCP_REGION-docker.pkg.dev/$GCP_PROJECT/$GCP_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
          docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT/$GCP_REGISTRY/$IMAGE_NAME:latest
          docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT/$GCP_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
