# https://github.com/antonputra/lesson-087/blob/main/.github/workflows/gcp.yml
---
name: GCP - Artifact Registry
on:
  push:
    branches: [main]
jobs:
  build-push-artifact-registry:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: goba2
      PROJECT_ID: holmes-dev
      REGISTRY: holmes-container-registry
      REGION: northamerica-northeast1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker image build -t goba2:latest .
      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet
      - name: Push to Artifact Registry
        run: |-
          docker tag goba2:latest northamerica-northeast1-docker.pkg.dev/holmes-dev/holmes-container-registry/goba2:latest
          docker push northamerica-northeast1-docker.pkg.dev/holmes-dev/holmes-container-registry/goba2:latest
